services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
  app:
    build: './'
    container_name: app
    restart: always
    depends_on:
      - db
      - mongodb_migration
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  mongodb_migration:
    build: './mongoInit'
    depends_on:
      - db